modeling_data_path: data/modeling
model_artifact_path: model_artifacts/model.pkl

train_set:
  path: "@format {this.modeling_data_path}/"
  filename: train_set.parquet
test_set:
  path: "@format {this.modeling_data_path}/"
  filename: test_set.parquet

metrics:
  path: data/metrics/performance.json
