stages:
  get-lyrics:
    cmd: reproml etl get-lyrics
    deps:
      - reproml/etl/lyrics/_lyrics.py
    outs:
    - data/raw/lyrics/

  prepro-lyrics:
    cmd: reproml prepro process
    deps:
    - reproml/preprocess/_preprocess.py
    - data/raw/lyrics/
    outs:
    - data/processed/lyrics

  split-lyrics:
    cmd: reproml prepro split
    deps:
    - reproml/preprocess/_preprocess.py
    - data/processed/lyrics/
    outs:
    - data/modeling/train_set.parquet
    - data/modeling/test_set.parquet

  train-model:
    cmd: reproml ml train
    deps:
    - data/modeling/train_set.parquet
    - reproml/ml/_ml.py
    outs:
    - model_artifacts/model.pkl

  validate-model:
    cmd: reproml validate metrics
    deps:
      - model_artifacts/model.pkl
      - data/modeling/test_set.parquet
    metrics:
    - data/metrics/performance.json
