[tool.black]
line-length = 105
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.coverage.paths]
source = ["reproml", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["reproml"]

[tool.coverage.report]
show_missing = true

[tool.isort]
profile = "black"
line_length = 105
skip = ["conf.py"]

[tool.mypy]
python_version = 3.8
check_untyped_defs = true
# It is recommended that ignore_missing_imports is applied on the module level using
# [[tool.mypy.overrides]] rather than the global level as shown here.
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
